<Project>
  <PropertyGroup>
    <_IsWpfTempProject Condition="$([System.String]::new('$(MSBuildProjectName)').ToLowerInvariant().Contains('wpftmp'))">true</_IsWpfTempProject>
  </PropertyGroup>
  <Target Name="CoreCompile" Condition="'$(_IsWpfTempProject)' == 'true'" />
  <Target Name="MarkupCompilePass2ForMainAssembly" />
</Project>
